name: Sync Fork (Multi-branch with Auto PR & Upstream Fallback)

on:
  schedule:
    - cron: '0 18 * * *'   # 每天北京时间 02:00 (UTC 18:00)
  workflow_dispatch:       # 允许手动触发

jobs:
  sync:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        branch: [main, dev]   # 需要同步的分支列表
    steps:
      # 1. 检出当前 fork 仓库代码
      - name: Checkout target repo
        uses: actions/checkout@v4
        with:
          persist-credentials: false
          fetch-depth: 0

      # 2. 配置 Git 用户信息
      - name: Set up Git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

      # 3. 自动检测上游仓库地址，如果失败则使用手写的备用地址
      - name: Detect or fallback upstream repo
        run: |
          # 手写的备用上游仓库地址（请改成你的上游仓库）
          FALLBACK="https://github.com/原作者/仓库名.git"

          # 调用 GitHub API 获取 parent 仓库地址
          UPSTREAM=$(curl -s https://api.github.com/repos/${{ github.repository }} \
            | jq -r '.parent.clone_url // empty')

          # 如果没获取到，就用手写的地址
          if [ -z "$UPSTREAM" ]; then
            echo "⚠️ 未检测到 fork 上游，使用备用地址: $FALLBACK"
            UPSTREAM=$FALLBACK
          else
            echo "✅ 自动检测到上游仓库: $UPSTREAM"
          fi

          # 添加并 fetch 上游
          git remote add upstream $UPSTREAM
          git fetch upstream

      # 4. 创建同步分支并合并上游更新
      - name: Create sync branch
        run: |
          BRANCH="sync-${{ matrix.branch }}-$(date +%Y%m%d%H%M%S)"
          git checkout ${{ matrix.branch }} || git checkout -b ${{ matrix.branch }} origin/${{ matrix.branch }}
          git merge upstream/${{ matrix.branch }} || true
          git checkout -b $BRANCH
          git push https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git $BRANCH
          echo "BRANCH=$BRANCH" >> $GITHUB_ENV

      # 5. 自动创建 Pull Request
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v6
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: "Sync fork with upstream/${{ matrix.branch }}"
          branch: ${{ env.BRANCH }}
          title: "🔄 Sync fork: ${{ matrix.branch }}"
          body: |
            This PR was automatically created to sync changes from upstream/${{ matrix.branch }}.
            Please review and merge.
          base: ${{ matrix.branch }}
